version: '3'
services:
  db_postgres:
    image: postgres
    ports:
      - 35432:5432
    restart: always
    env_file:
      - .env.development
  app:
    build: .
    restart: always
    ports:
      - 8080:8080